### ISSUE TITLE
.XAP file

### ISSUE THREAD

**Issue by barneh** [bilbob74/8Pass#10]
Is it possible to put an .XAP file for download, so people ho don't have the tool to fork an build can install the app?

**Comment by frostieDE** [comment]
This is possible but you need to have an developer-registered device to deploy the app. But we will publish the app in the near future ;-)

**Comment by barneh** [comment]
Okay!
Sounds great!

**Comment by barneh** [comment]
What is happening to this @frostieDE? 
"But we will publish the app in the near future ;-)"
