### ISSUE TITLE
Commiting

### ISSUE THREAD

**Issue by barneh** [bilbob74/8Pass#13]
Hi!
I'm fairly new to GitHub.
But I have made a language file for Swedish that I would like to commit, but I get the error that I don't have permission. What are I'm doing wrong?

**Comment by bilbob74** [comment]
There should be a Pull Request feature in your GIT client. With this you commit your changes to project.

Von meinem Windows Phone gesendet
________________________________
Von: barneh<mailto:notifications@github.com>
Gesendet: ‎15.‎04.‎2015 14:46
An: bilbob74/8Pass<mailto:8Pass@noreply.github.com>
Betreff: [8Pass] Commiting (#13)

Hi!
I'm fairly new to GitHub.
But I have made a language file for Swedish that I would like to commit, but I get the error that I don't have permission. What are I'm doing wrong?

---
Reply to this email directly or view it on GitHub:
https://github.com/bilbob74/8Pass/issues/13

**Comment by barneh** [comment]
Looks lite I have fucked it up real good now! Sorry!

Seems that I have been on the wrong branch and have now created a merge 41 commits into gh-pages from master.

And I don't know how to revert this either... :(

**Comment by bilbob74** [comment]
No Problem. I will close your Pull Request. You could make another Pull Request with the correct changes.

**Comment by barneh** [comment]
![pullrequest](https://cloud.githubusercontent.com/assets/7715121/7176956/45cf625e-e423-11e4-8085-fe37ae213c1c.png)

I have a conflict with the master?

**Comment by bilbob74** [comment]
Try to click on "Send pull request". I will try to resolve the conflict manually

**Comment by barneh** [comment]
![pullrequestdone](https://cloud.githubusercontent.com/assets/7715121/7177280/9bd6660a-e425-11e4-9b11-cd6a793176ec.png)

I tried.... but got an error :disappointed:

**Comment by bilbob74** [comment]
I have changed a setting. Please try again.

**Comment by barneh** [comment]
Sam error.

**Comment by bilbob74** [comment]
Than i have no idea, whats going wrong. Could you send your changes via E-Mail or OneDrive?

**Comment by barneh** [comment]
Looks like it vent through now right?

**Comment by bilbob74** [comment]
Yes, now i have a pull request with the correct files. I will merge this request. Since it seems to be a slightly different version of English instead of Swedish, i will open a additional Issue. With this Issue we can correct the language file if you want.

**Comment by barneh** [comment]
Great!
Yes I did that because I just wanted to get the throughput towards the git project first.
So I will do a complete translation later on.
