### ISSUE TITLE
Deploy error "package could not be registered"

### ISSUE THREAD

**Issue by frostieDE** [bilbob74/8Pass#4]
When I try to deploy the app to the emulator, Visual Studio says that the package could not be registed (or whatever this message is in English -> the German one is "Das Paket konnte nicht registriert werden")

**Comment by bilbob74** [comment]
To which Paket refers the error?

BTW: Du kannst gerne auch auf Deutsch schreiben. Ich komme aus der Nähe von München :-)

**Comment by frostieDE** [comment]
This error occurs when I try to deploy the app (not the class library) to the emulator. The internet says that this error comes from migrating to 8.1 :/ maybe I will fix this in the next days..

I could write in German (I am from Aachen) but I guess that would not be very helpful for non-German contributors ;-)

**Comment by bilbob74** [comment]
Hmm after the Migration on my PC, there was no such error. But i didnt have deployed it to the Emulator, i deployed it only direct to a Device, because its only a Windows 8.1 Home PC. For the Emulator i need a Pro Version. It would be great, if you could fix it.

**Comment by frostieDE** [comment]
Okay, I will fix this in the next days. But solutions on the internet say that I have to re-create the whole project :/

**Comment by mroddy** [comment]
Hello both, I was having the same issue, I've found a solution in that the following values need to be identical:
PhonePublisherId in Package.appxmanifest and PublisherID in WMAppManifest.xml
PhoneProductId in Package.appxmanifest and ProductID in WMAppManifest.xml
I used the values from WMAppManifest.xml and copied these over, not sure which is best to chose.

**Comment by frostieDE** [comment]
Hey, if this solves the problem please open a pull request with this change. I will merge this in a few days when I am back from holidays. Thanks!
